spring:
  data:
    mongodb:
      uri: mongodb+srv://esp_admin:dupa1234@mongo-storage.7zu4pph.mongodb.net/?retryWrites=true&w=majority
      database: esp32metrics

# App Properties
com:
  example:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000